apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: p805q7qmt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/p805q7qmt-java-quarkus-gitops